In [27]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt

In [28]:
from sklearn.datasets import load_breast_cancer
c1 = load_breast_cancer()
df = pd.DataFrame(c1['data'],columns=c1['feature_names'])
label = c1['target']

In [52]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [29]:
df.shape, label.shape

((569, 30), (569,))

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df, label, test_size = 0.3, random_state = 12)

In [33]:
x_train.shape

(398, 30)

# First train using Logistic Regression

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
LM = LogisticRegression()
LM.fit(x_train, y_train)
LM_pred = LM.predict(x_test)
print(accuracy_score(y_test,LM_pred))

0.9415204678362573


C:\Users\Dr.PVVK\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Apply GA to solve the same Problem

In [58]:
# Initialize Population
pop = []
for i in range(200):      # pop_size = 10
    chromosome = np.ones(30, dtype = np.intc)  # num_features = 5
    chromosome[:int(0.3*30)] = False
    np.random.shuffle(chromosome)
    pop.append(chromosome)

In [59]:
chromosome

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1], dtype=int32)

In [60]:
pop

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 1, 1, 0, 1, 1, 1], dtype=int32),
 array([0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1], dtype=int32),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 1, 0], dtype=int32),
 array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1], dtype=int32),
 array([0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 1, 1], dtype=int32),
 array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 1], dtype=int32),
 array([1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 0, 0, 1], dtype=int32),
 array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 1, 1, 1], dtype=int32),
 array([0, 1, 1, 0, 0, 1, 0, 1, 

# We have to select two sets of chromosomes as parents...
## We need Fitness Function and its output as scores

In [61]:
scores = []
for chromosome in pop:
    LM.fit(x_train.iloc[:,chromosome],y_train)
    LM_predt = LM.predict(x_test.iloc[:,chromosome])
    scores.append(accuracy_score(y_test,LM_predt))
scores, pop = np.array(scores), np.array(pop)

In [62]:
x_train.iloc[:,chromosome].shape

(398, 30)

In [63]:
inds = np.argsort(scores)

In [65]:
inds

array([  0, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 126, 148, 125, 123,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 124, 101, 149, 151, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 176, 150, 175, 173, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 174, 100,  99,  98,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  25,  47,  24,  22,   1,   2,   3,   4,
         5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  23,  48,  49,  50,  77,  78,  79,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  76,  75,  74,  73,  51,  52,  53,  54,  5

In [66]:
list(scores[inds][::-1])

[0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824561403,
 0.8771929824

In [68]:
list(pop[inds,:][::-1])

[array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 0], dtype=int32),
 array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 1], dtype=int32),
 array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 0, 1, 1], dtype=int32),
 array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 0, 1], dtype=int32),
 array([1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 1, 0, 1], dtype=int32),
 array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 1, 1], dtype=int32),
 array([0, 0, 0, 0, 1, 1, 1, 1, 

In [69]:
pop_after_fit = list(pop[inds,:][::-1])

# Select Next Gen Pop

In [70]:
pop_nextgen = []
for i in range(100):
    pop_nextgen.append(pop_after_fit[i])

In [71]:
len(pop_nextgen),pop_nextgen

(100,
 [array([1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
         0, 1, 0, 1, 1, 1, 1, 1], dtype=int32),
  array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
         1, 1, 0, 1, 1, 1, 1, 1], dtype=int32),
  array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
         1, 1, 0, 1, 1, 0, 1, 0], dtype=int32),
  array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
         1, 1, 1, 0, 1, 0, 0, 1], dtype=int32),
  array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
         1, 1, 0, 1, 0, 0, 1, 1], dtype=int32),
  array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
         1, 1, 0, 1, 1, 1, 0, 1], dtype=int32),
  array([1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
         0, 1, 1, 1, 1, 1, 0, 1], dtype=int32),
  array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
         1, 1, 1, 0, 1, 1, 1, 1], dtype=int32),
  array([0

# Crossover Operation

In [72]:
pop_nextgeneration = pop_nextgen
for i in range(len(pop_nextgen)):
    child = pop_nextgen[i]
    child[3:7] = pop_nextgen[(i+1)%len(pop_nextgen)][3:7]
    pop_nextgeneration.append(child)

In [73]:
len(pop_nextgeneration)

200

In [74]:
pop_nextgeneration

[array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 1, 1, 1], dtype=int32),
 array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 0], dtype=int32),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 1], dtype=int32),
 array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 0, 1, 1], dtype=int32),
 array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 0, 1], dtype=int32),
 array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 1, 0, 1], dtype=int32),
 array([1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 1, 1, 1, 1], dtype=int32),
 array([0, 0, 0, 1, 1, 1, 0, 1, 