# Supervised Model

In [89]:
import numpy as np
from numpy import linalg as la
import matplotlib.pyplot as plt

In [90]:
C1 = np.array([[1,2,3,4,5],[2,3,3,5,5]]).T

In [91]:
C1

array([[1, 2],
       [2, 3],
       [3, 3],
       [4, 5],
       [5, 5]])

In [92]:
C2 = np.array([[4,5,5,3,5,6],[2,0,2,2,3,3]]).T

In [93]:
C2.shape

(6, 2)

In [94]:
X = np.concatenate((C1, C2))

In [95]:
X

array([[1, 2],
       [2, 3],
       [3, 3],
       [4, 5],
       [5, 5],
       [4, 2],
       [5, 0],
       [5, 2],
       [3, 2],
       [5, 3],
       [6, 3]])

In [96]:
M=len(X[0])
n1 = len(C1)
n2 = len(C2)
print(n1)
print(n2)

5
6


In [97]:
M

2

# Calculate Between Class Matrix SB.

In [98]:
C1_m = np.mean(C1,0)
C2_m = np.mean(C2,0)
X_m = np.mean(X,0)

In [99]:
X_m

array([3.90909091, 2.72727273])

# Calculate Between Class Variance

In [100]:
SB1 = n1*(np.reshape((C1_m-X_m),(2,1)))*(C1_m-X_m)

In [101]:
SB2 = n2*(np.reshape((C2_m-X_m),(2,1)))*(C2_m-X_m)

In [102]:
SB = SB1+SB2

In [103]:
SB

array([[ 7.57575758, -7.27272727],
       [-7.27272727,  6.98181818]])

# Calculating the Within-Class Variance (SW)!

# mean-centering data

In [104]:
d1 = C1-C1_m
d2 = C2-C2_m

In [105]:
d1

array([[-2. , -1.6],
       [-1. , -0.6],
       [ 0. , -0.6],
       [ 1. ,  1.4],
       [ 2. ,  1.4]])

# Class-Independent Method: LDA Computation!

# within-class variance for each class!

In [106]:
#SW1 = (d1.T)*d1

In [107]:
SW1 = np.matmul((d1.T),d1)
SW2 = np.matmul((d2.T),d2)
SW = SW1+SW2

In [108]:
SW

array([[15.33333333,  9.        ],
       [ 9.        , 13.2       ]])

In [109]:
 SW_inv = np.linalg.inv(SW) 

In [110]:
#A = SB/SW

# LDA Transformation Matrix W

In [111]:
W = np.matmul((SW_inv).T,SB)

In [112]:
W

array([[ 1.36288752, -1.30837202],
       [-1.48020568,  1.42099745]])

# Calculate Eigen Values & Eigen Vectors of W

In [113]:
u,v = np.linalg.eig(W)
print(v)
print(u)

[[-0.69253183  0.67735211]
 [-0.72138732 -0.73565897]]
[-2.22044605e-16  2.78388498e+00]


# Projecting original data on to a lower dimensional space

In [114]:
V1 = v[:,0]
V2 = v[:,1]

In [115]:
np.reshape(V2,(2,1))

array([[ 0.67735211],
       [-0.73565897]])

In [116]:
y1 = np.matmul(C1,np.reshape(V1,(2,1)))

In [117]:
y1.shape

(5, 1)

In [118]:
y2 = np.matmul(C2,np.reshape(V1,(2,1)))

In [119]:
y2

array([[-4.21290195],
       [-3.46265914],
       [-4.90543378],
       [-3.52037013],
       [-5.6268211 ],
       [-6.31935293]])

In [120]:
mse_C1 = np.sum((C1-y1)**2)/len(C1[0])

In [121]:
mse_C1

366.9872956074347

In [122]:
mse_C2 = np.sum((C2-y2)**2)/len(C2[0])

In [123]:
mse_C2

417.20951462459556

In [124]:
from scipy.stats import norm
y2_pdf = norm.pdf(y2)

In [125]:
y2_pdf

array([[5.58293984e-05],
       [9.93831685e-04],
       [2.37484394e-06],
       [8.12461973e-04],
       [5.31846295e-08],
       [8.49775198e-10]])