# Principle Component Analysis

In [1]:
import numpy as np
from numpy import linalg as la
import matplotlib.pyplot as plt

In [3]:
#x = np.array([[1,0,-1],[-1,1,0],[0,1,1],[1,-1,1]]).T
x = np.array([[1,0,-1],[-1,1,0]]).T

In [14]:
x

array([[ 1, -1],
       [ 0,  1],
       [-1,  0]])

In [6]:
x_m = np.mean(x,0)

# axis = 0 means along the rows and axis = 1 means working along the colums.

In [8]:
x_m

array([0., 0.])

# S1. Calculate the Covariance Matrix 'C'

In [10]:
C = np.cov(x.T)

In [16]:
C_my = np.matmul(x.T,x)

In [17]:
#C_My = x.T*x

In [18]:
C_my

array([[ 2, -1],
       [-1,  2]])

In [19]:
C

array([[ 1. , -0.5],
       [-0.5,  1. ]])

In [20]:
#x = np.array([[0, 2], [1, 1], [2, 0]]).T

In [21]:
#np.cov(x.T)

# Calculate Eigen Values & Eigen Vectors

In [23]:
u,v = la.eig(C)
print(v)
print(u)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[1.5 0.5]


# Form Transformation Matrix from top n eigen values

In [37]:
A = np.array([v[:,1]])
print(A)

[[0.70710678 0.70710678]]


# transform the input vectors to obtain vectors in two dimensions to complete the PCA operation

In [38]:
Y = np.matmul(A,(x-x_m).T)

In [39]:
Y.T.shape

(3, 1)

In [40]:
x.shape

(3, 2)

# now reconstruct the original vectors and compute the mean square error between the original 2-dimensional vectors and the reconstructed 2-dimensional vectors.

In [41]:
x_recon = np.matmul(A.T,Y).T

In [42]:
mse = np.sum((x-x_recon)**2)/len(x[0])

In [44]:
mse

1.5000000000000002

In [45]:
x_recon

array([[-1.57009246e-16, -1.57009246e-16],
       [ 5.00000000e-01,  5.00000000e-01],
       [-5.00000000e-01, -5.00000000e-01]])

In [46]:
from sklearn.decomposition import PCA

In [48]:
pca = PCA(n_components=2)

In [49]:
pca.fit(x)

PCA(n_components=2)

In [51]:
print(pca.explained_variance_ratio_)

[0.75 0.25]


In [52]:
print(pca.singular_values_)

[1.73205081 1.        ]
